
    create table Cancha (
        cancha_id integer generated by default as identity (start with 1),
        cancha_nombre varchar(255),
        cancha_telefono varchar(255),
        cancha_esta_iluminada boolean,
        color_codigo varchar(255),
        primary key (cancha_id)
    )

    create table Color (
        codigo varchar(255) not null,
        descripcion varchar(255),
        primary key (codigo)
    )

    create table Constructor (
        constructor_codigo integer generated by default as identity (start with 1),
        constructor_domicilio varchar(255),
        constructor_nombre varchar(255),
        primary key (constructor_codigo)
    )

    create table Jugador (
        jugador_id integer generated by default as identity (start with 1),
        jugador_apellido varchar(255),
        jugador_domicilio varchar(255),
        jugador_fecha_de_nacimiento timestamp,
        jugador_nombre varchar(255),
        paleta_paleta_codigo integer,
        primary key (jugador_id)
    )

    create table Paleta (
        paleta_codigo integer generated by default as identity (start with 1),
        paleta_grosor double,
        paleta_nombre varchar(255),
        color_codigo varchar(255),
        constructor_constructor_codigo integer,
        primary key (paleta_codigo)
    )

    create table Partido (
        codigo integer generated by default as identity (start with 1),
        partido_fecha_fin timestamp,
        partido_fecha_inicio timestamp,
        cancha_cancha_id integer,
        color_codigo varchar(255),
        primary key (codigo)
    )

    create table Partidos_Jugador (
        partido_codigo integer,
        jugador_jugador_id integer,
        colorPaleta_codigo varchar(255),
        paletaUtilizada_paleta_codigo integer,
        primary key (partido_codigo, jugador_jugador_id)
    )

    create table Reserva (
        reserva_fecha_fin timestamp,
        reserva_fecha_inicio timestamp,
        cancha_cancha_id integer not null,
        jugador_jugador_id integer,
        primary key (cancha_cancha_id)
    )

    alter table Cancha 
        add constraint FK_qk4c15mkldajgmeoyhrkuhn6c 
        foreign key (color_codigo) 
        references Color

    alter table Jugador 
        add constraint FK_b4cjnckqrrj0u02o4idvn2adv 
        foreign key (paleta_paleta_codigo) 
        references Paleta

    alter table Paleta 
        add constraint FK_9j19oqf4w3iwpf7f8v6vs7qj6 
        foreign key (color_codigo) 
        references Color

    alter table Paleta 
        add constraint FK_8oat3kj85kvnqv5n25wyrj6c7 
        foreign key (constructor_constructor_codigo) 
        references Constructor

    alter table Partido 
        add constraint FK_kbkaqhyv84fkayueqh4knj8bm 
        foreign key (cancha_cancha_id) 
        references Cancha

    alter table Partido 
        add constraint FK_h6s33mg58krpnrwx5ku769t4j 
        foreign key (color_codigo) 
        references Color

    alter table Partidos_Jugador 
        add constraint FK_j9wvs59xmbmuhgcojyx21152g 
        foreign key (partido_codigo) 
        references Partido

    alter table Partidos_Jugador 
        add constraint FK_6e4b5mvmmwyrb9oupwjv7ytww 
        foreign key (jugador_jugador_id) 
        references Jugador

    alter table Partidos_Jugador 
        add constraint FK_3p1hgki8vf02bc2tovcydsn49 
        foreign key (colorPaleta_codigo) 
        references Color

    alter table Partidos_Jugador 
        add constraint FK_t8a21qic5yyoa5idp55w65cab 
        foreign key (paletaUtilizada_paleta_codigo) 
        references Paleta

    alter table Reserva 
        add constraint FK_bo03dt58k9ig0jyex0hs46wk 
        foreign key (cancha_cancha_id) 
        references Cancha

    alter table Reserva 
        add constraint FK_th8p6wpiv2gnf8urg1t6xrk1o 
        foreign key (jugador_jugador_id) 
        references Jugador
